server:
  port: 8080

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/testlogin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  output.ansi.enabled: always

  jpa:
    hibernate:
      ddl-auto: update # (1) ??? ?? ??
      use-new-id-generator-mappings: false
    show-sql: false # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print
    #        dialect: org.hibernate.dialect.MariaDB103Dialect


  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: "/static/**"

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  resources:
    cache:
      cachecontrol:
        duration: 1

#file:
#  item:
#    dir: item
#
#  banner:
#    dir: banner

itemImgLocation: D:/Programming/testLoginSessionVer/src/main/resources/static/img/item
bannerImgLocation: D:/Programming/testLoginSessionVer/src/main/resources/static/img/banner
uploadPath: file:///D:/Programming/testLoginSessionVer/src/main/resources/static


jwt:
  secret: n0syh2pcj1W9hGmeXsEFrfSiSqh3BE8ZOV4HOkAM2yFpFSQ9E3pWV4TQCgwvAmYaTveCepecwcZpBbFFdjfakskejrlfrpgodigksmsrjswlcka

